# .github/workflows/main.yml

name: Buildozer Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 明确使用Java 17，以满足现代Android工具链的要求
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 安装Android SDK命令行工具，这是基础
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "buildozer==1.5.0" "kivy[base,sdl2]==2.3.0" "beautifulsoup4" "cython==0.29.34"

    # --- 核心修复：在Buildozer运行前，强制安装所有必需的SDK组件 ---
    - name: Install Android Build Tools and Platform Tools
      run: |
        # 我们不再依赖buildozer去安装，我们自己来！
        # 这会安装我们指定的build-tools, 最新的platform-tools, 和一个编译用的平台SDK
        # 'yes' 命令会自动接受所有弹出的许可证
        echo "y" | sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Initialize Buildozer
      run: buildozer init
    
    - name: Configure buildozer.spec
      run: |
        sed -i 's/#title = My Application/title = 刷题小程序/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = quizapp/' buildozer.spec
        sed -i 's/#source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,htm,html,ttf/' buildozer.spec
        sed -i 's/#requirements = python3,kivy/requirements = python3,kivy==2.3.0,beautifulsoup4/' buildozer.spec
        sed -i 's/#orientation = landscape/orientation = portrait/' buildozer.spec
        sed -i 's/#fullscreen = 0/fullscreen = 1/' buildozer.spec
        # 明确告诉buildozer我们已经安装了哪些版本，让它直接使用
        echo "android.build_tools = 34.0.0" >> buildozer.spec
        echo "android.platform = 34" >> buildozer.spec

    # --- 关键修改：删除所有之前失败的许可证接受步骤 ---
    # 我们已经在上一步的安装命令中处理了许可证，不再需要这些了
    # - name: Force accept Android SDK licenses ... (整个步骤被删除)

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-apk
        path: bin/*.apk
