# .github/workflows/main.yml

name: Buildozer Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # --- 关键步骤 1：明确设置一个现代的、兼容的Java版本 ---
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "buildozer==1.5.0" "kivy[base,sdl2]==2.3.0" "beautifulsoup4" "cython==0.29.34"

    - name: Initialize Buildozer
      run: buildozer init
    
    - name: Configure buildozer.spec
      run: |
        sed -i 's/#title = My Application/title = 刷题小程序/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = quizapp/' buildozer.spec
        sed -i 's/#source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,htm,html,ttf/' buildozer.spec
        sed -i 's/#requirements = python3,kivy/requirements = python3,kivy==2.3.0,beautifulsoup4/' buildozer.spec
        sed -i 's/#orientation = landscape/orientation = portrait/' buildozer.spec
        sed -i 's/#fullscreen = 0/fullscreen = 1/' buildozer.spec
        echo "android.build_tools = 34.0.0" >> buildozer.spec
        # --- 关键步骤 2：强制p4a更新其构建配方，打破缓存循环 ---
        echo "android.skip_update = False" >> buildozer.spec

    # --- 关键步骤 3：现在这个命令将在正确的Java 17环境下运行 ---
    - name: Force accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-apk
        path: bin/*.apk
