name: Buildozer Android APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install buildozer beautifulsoup4 kivy==2.3.0 cython
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-dev libffi-dev libssl-dev libbz2-dev libncurses5-dev libsqlite3-dev libreadline-dev zlib1g-dev libncursesw5-dev libgdbm-compat-dev liblzma-dev libsqlite3-dev tk-dev libdb-dev libexpat1-dev

    # --- 关键修改：这是最终的、最可靠的解决方案 ---
    - name: Accept Android SDK licenses
      run: |
        # Buildozer会把SDK下载到/home/runner/.buildozer/android/platform/android-sdk
        # 我们提前创建好licenses文件夹
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
        # 将行业标准的、已接受的许可证哈希写入文件
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-apk
        path: bin/*.apk
