name: Buildozer Android APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 更新checkout到v4

    - name: Set up Python
      uses: actions/setup-python@v5 # 更新setup-python到v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install buildozer beautifulsoup4 kivy==2.3.0
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-dev libffi-dev libssl-dev libbz2-dev libncurses5-dev libsqlite3-dev libreadline-dev zlib1g-dev libncursesw5-dev libgdbm-compat-dev liblzma-dev libsqlite3-dev tk-dev libdb-dev libexpat1-dev

    - name: Initialize Buildozer
      run: buildozer init
    
    - name: Configure buildozer.spec
      run: |
        sed -i 's/#title = My Application/title = 刷题小程序/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = quizapp/' buildozer.spec
        sed -i 's/#source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,htm,html,ttf/' buildozer.spec
        sed -i 's/#requirements = python3,kivy/requirements = python3,kivy==2.3.0,beautifulsoup4,hostpython3/' buildozer.spec
        sed -i 's/#orientation = landscape/orientation = portrait/' buildozer.spec
        sed -i 's/#fullscreen = 0/fullscreen = 1/' buildozer.spec
        echo "android.api = 31" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 24" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      # --- 关键修改：将版本号从 v3 更新到 v4 ---
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-apk
        path: bin/*.apk
